- name: Set up Python
  uses: actions/setup-python@v2
  with:
    python-version: 3.11


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  data-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have any dependencies, specify them in requirements.txt

      - name: Run Data Analysis
        run: python data_analysis_script.py  # Replace with the actual name of your data analysis script

      - name: Commit and Push Changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add orcl-sma.csv orcl-rsi.csv
          git commit -m "Update SMA and RSI data [skip ci]"
          git push
