name: ain1001 project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sma_rsi_calculator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sma_rsi
        run: python sma_rsi_calculator.py

      - name: Commit and Push Changes
        run: |
          git add orcl-sma.csv orcl-rsi.csv
          git commit -m "Update SMA and RSI data [skip ci]"
          git push
